-- CreateEnum
CREATE TYPE "ProrationMethod" AS ENUM ('PRORATED_BY_DAYS', 'LATEST_POLICY_IN_YEAR');

-- AlterTable
-- entitled_days is REPLACED by policy-derived entitlement. A per-employee
-- override column takes its place for the cases that genuinely deviate.
ALTER TABLE "leave_balances" DROP COLUMN "entitled_days",
ADD COLUMN     "carried_forward_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "entitlement_override_days" DECIMAL(5,2);

-- AlterTable
ALTER TABLE "leave_requests" ADD COLUMN     "applied_policy_id" TEXT,
ADD COLUMN     "auto_approved" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
-- default_annual_days was the single mutable quota. It moves to
-- leave_type_policies so quota changes keep their history.
ALTER TABLE "leave_types" DROP COLUMN "default_annual_days",
ADD COLUMN     "proration_method" "ProrationMethod" NOT NULL DEFAULT 'PRORATED_BY_DAYS';

-- CreateTable
CREATE TABLE "leave_type_policies" (
    "id" TEXT NOT NULL,
    "leave_type_id" TEXT NOT NULL,
    "quota_days" DECIMAL(5,2) NOT NULL,
    "approval_required" BOOLEAN NOT NULL DEFAULT true,
    "carry_forward_enabled" BOOLEAN NOT NULL DEFAULT false,
    "carry_forward_max_days" DECIMAL(5,2),
    "min_notice_days" INTEGER NOT NULL DEFAULT 0,
    "effective_from" DATE NOT NULL,
    "effective_to" DATE,
    "notes" TEXT,
    "created_by_id" TEXT,
    "updated_by_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "leave_type_policies_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "leave_type_policies_leave_type_id_effective_to_idx" ON "leave_type_policies"("leave_type_id", "effective_to");

-- CreateIndex
CREATE UNIQUE INDEX "leave_type_policies_leave_type_id_effective_from_key" ON "leave_type_policies"("leave_type_id", "effective_from");

-- AddForeignKey
ALTER TABLE "leave_type_policies" ADD CONSTRAINT "leave_type_policies_leave_type_id_fkey" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "leave_type_policies" ADD CONSTRAINT "leave_type_policies_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "leave_type_policies" ADD CONSTRAINT "leave_type_policies_updated_by_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "leave_requests" ADD CONSTRAINT "leave_requests_applied_policy_id_fkey" FOREIGN KEY ("applied_policy_id") REFERENCES "leave_type_policies"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- HAND-WRITTEN ADDITION (not generated by Prisma)
--
-- Makes overlapping policy periods for the same leave type IMPOSSIBLE at the
-- database level, not merely discouraged by a service check.
--
-- Prisma has no syntax for an exclusion constraint, so this is maintained by
-- hand. If this migration is ever regenerated, re-add this block.
-- Same convention as the partial unique index on employment_assignments.
--
-- How it reads: no two rows may share a leave_type_id AND have overlapping
-- date ranges. `&&` is the range-overlap operator.
--
-- daterange(from, to, '[]') treats both endpoints as inclusive, and a NULL
-- upper bound as unbounded — which is exactly what effective_to = NULL means
-- ("still current"). Postgres normalises inclusive discrete ranges to
-- half-open, so Jan 1–Jun 30 and Jul 1–onwards sit flush without overlapping.
--
-- btree_gist is required because the constraint mixes an equality test on a
-- plain text column with a range-overlap test.
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE "leave_type_policies"
  ADD CONSTRAINT "leave_type_policies_no_overlap"
  EXCLUDE USING gist (
    "leave_type_id" WITH =,
    daterange("effective_from", "effective_to", '[]') WITH &&
  );
